"""
PR Template Builder
--------------------
Generates a rich, structured Pull Request body from the AI analysis
and remediation output.
"""

from datetime import datetime, timezone


RISK_EMOJI = {
    "LOW":      "🟢",
    "MEDIUM":   "🟡",
    "HIGH":     "🟠",
    "CRITICAL": "🔴",
}

VERIFY_EMOJI = {True: "✅", False: "❌"}


def build_pr_body(
    summary: dict,
    analysis: dict,
    remediation: dict,
    verify_ok: bool,
    verify_output: str,
) -> str:
    risk      = analysis.get("risk_level", "UNKNOWN")
    risk_icon = RISK_EMOJI.get(risk, "⚪")
    counts    = summary.get("counts", {})
    now       = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    file_changes  = remediation.get("file_changes",  [])
    skipped       = remediation.get("skipped_changes", [])

    lines = [
        f"## 🤖 AI-Driven Infrastructure Drift Remediation",
        f"",
        f"> **Detected:** {now}  |  **Environment:** Azure Staging",
        f"> **Risk Level:** {risk_icon} `{risk}`  |  **Terraform Validation:** {VERIFY_EMOJI[verify_ok]}",
        f"",
        f"---",
        f"",
        f"### 📊 Drift Summary",
        f"",
        f"| Action   | Count |",
        f"|----------|-------|",
        f"| ➕ Add     | {counts.get('add', 0)} |",
        f"| ✏️  Change | {counts.get('change', 0)} |",
        f"| 🗑️  Destroy | {counts.get('destroy', 0)} |",
        f"| 🔄 Replace | {counts.get('replace', 0)} |",
        f"| ⚠️  Drifted | {counts.get('drift', 0)} |",
        f"",
        f"---",
        f"",
        f"### 🧠 AI Analysis",
        f"",
        f"**Summary:** {analysis.get('summary', 'N/A')}",
        f"",
        f"**Root Cause:** {analysis.get('root_cause', 'N/A')}",
        f"",
        f"**Security Impact:** {analysis.get('security_impact', 'None')}",
        f"",
        f"**Cost Impact:** {analysis.get('cost_impact', 'None')}",
        f"",
    ]

    # Recommended actions
    actions = analysis.get("recommended_actions", [])
    if actions:
        lines += ["**Recommended Actions:**", ""]
        for a in actions:
            lines.append(f"- {a}")
        lines.append("")

    lines += [
        f"---",
        f"",
        f"### 📝 Files Modified ({len(file_changes)})",
        f"",
    ]

    for fc in file_changes:
        lines += [
            f"<details>",
            f"<summary><code>{fc['path']}</code> — {fc.get('description', '')}</summary>",
            f"",
            f"```hcl",
            fc.get("content", "# No content"),
            f"```",
            f"</details>",
            f"",
        ]

    if skipped:
        lines += [
            f"---",
            f"",
            f"### ⚠️ Skipped Changes (Manual Review Required)",
            f"",
        ]
        for s in skipped:
            lines.append(f"- **`{s.get('resource', 'unknown')}`** — {s.get('reason', 'No reason given')}")
        lines.append("")

    # Verification
    lines += [
        f"---",
        f"",
        f"### {VERIFY_EMOJI[verify_ok]} Terraform Validation",
        f"",
        f"```",
        verify_output[:2000] if verify_output else "No output captured",
        f"```",
        f"",
        f"---",
        f"",
        f"### ✅ Review Checklist",
        f"",
        f"- [ ] AI analysis risk level reviewed",
        f"- [ ] File changes reviewed for correctness",
        f"- [ ] Skipped changes handled manually (if any)",
        f"- [ ] `terraform plan` output reviewed",
        f"- [ ] Safe to apply to Staging",
        f"",
        f"---",
        f"",
        f"*Generated by [AI Drift Remediation Bot](.github/workflows/drift-detection.yml) · {now}*",
    ]

    return "\n".join(lines)
